apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iris-autoscale
  name: iris-autoscale
spec:
  selector:
    matchLabels:
      app: iris-autoscale
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iris-autoscale
    spec:
      containers:
      - image: vmrcastro/iris-autoscale:latest
        imagePullPolicy: Always
        name: iris-autoscale
        ports:
        - containerPort: 52773
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: iris-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-autoscale
  # autoscale between 1 and 5 replicas
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # use a "Pods" metric
  - type: Pods
    pods:
      metricName: queue_size
      # target queue size of 10
      targetAverageValue: 10
---
apiVersion: v1
kind: Service
metadata:
  name: iris-autoscale-svc
spec:
  selector:
    app: iris-autoscale
  ports:
    - name: webserver
      protocol: TCP
      port: 52773
      targetPort: 52773
  type: LoadBalancer