apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iris-autoscale
  name: iris-autoscale
spec:
  selector:
    matchLabels:
      app: iris-autoscale
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iris-autoscale
      annotations:
        example.io/should_be_scraped: true
        example.io/scrape_port: "52773"
    spec:
      containers:
      - args:
        - --key /mnt/key/iris.key
        image: __CONTAINER_IMAGE__
        imagePullPolicy: Always
        name: iris-autoscale
        env:
        - name: ISC_CPF_MERGE_FILE
          value: /mnt/cpf/data_autoscale.cpf
        ports:
        - containerPort: 52773
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/key
          name: iris-key-secret
        - mountPath: /mnt/cpf
          name: iris-autoscale-cpf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: iris-key-secret
        secret:
          defaultMode: 420
          secretName: iris-key-secret
      - name: iris-autoscale-cpf
        configMap:
          name: iris-autoscale-cpf
---
apiVersion: v1
kind: Service
metadata:
  name: iris-autoscale-svc
spec:
  selector:
    app: iris-autoscale
  ports:
    - name: webserver
      protocol: TCP
      port: 52773
      targetPort: 52773
  type: LoadBalancer